[package]
name = "shovel-knight-ripper"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
binrw = "0.14.1"
clap = { version = "4.5.37", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
