[package]
name = "excavator_egui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
egui-async = "0.3.0"
egui_ltreeview = "0.6.0"
excavator_formats = { version = "0.1.0", path = "../excavator_formats" }
rfd = "0.17.2"
tokio = { version = "1.49.0", features = ["fs"] }
