[package]
name = "excavator_gdextension"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
excavator_formats = { version = "0.1.0", path = "../excavator_formats" }
godot = "0.4.5"
